### ISSUE TITLE
Heroku: heroku run fails - error connecting to dyno

### ISSUE THREAD

**Issue by fayazv** [taarifa/TaarifaTraders#4]
When creating schemas & facilities or even simple bash

```
heroku run python manage.py create_facility
heroku run bash
```

throws the following error:

```
Running `python manage.py create_facility` attached to terminal... up, run.7513
 !    
 !    Error connecting to dyno, see https://devcenter.heroku.com/articles/one-off-dynos#timeout-awaiting-process
...
Running `bash` attached to terminal... up, run.3239
 !    
 !    Error connecting to dyno, see https://devcenter.heroku.com/articles/one-off-dynos#timeout-awaiting-process
```

The above [link](https://devcenter.heroku.com/articles/one-off-dynos#timeout-awaiting-process) suggests to test connection to `rendezvous.runtime.heroku.com` on port **5000** using telnet

```
telnet rendezvous.runtime.heroku.com 5000
```

A successful connection looks like:

```
Trying 50.19.103.36...
Connected to ec2-50-19-103-36.compute-1.amazonaws.com.
Escape character is '^]'.
```

What seems to be the problem?

**Comment by kynan** [comment]
Normally that indicates that port 5000 is blocked on your end. Can you run the above telnet command successfully?

**Comment by fayazv** [comment]
The telnet command runs successfully and gives the output shown on the
heroku docs.

**Comment by kynan** [comment]
Not sure what might be going on. @dgorissen?

**Comment by dgorissen** [comment]
No idea, sorry

**Comment by markiliffe** [comment]
@dgorissen, @kynan can we have a call with @fayazv to work this out, I'm sure it will be a quick issue to resolve once we know what the issue it. On speaking to @fayazv, potentially he's having issues with port blocking on his current network, but he will get back to us.

**Comment by fayazv** [comment]
Ok. The issue was in the network I was connected (some ports are blocked for security reasons). I tried running the same code after connecting to my hotspot and it worked like a charm.
