### ISSUE TITLE
Setting up TaarifaTraders in AWS

### ISSUE THREAD

**Issue by fayazv** [taarifa/TaarifaTraders#6]
I managed setting up the `TaarifaAPI` and `TaarifaTraders` in AWS. 

When testing the API, I ran:

```
python taarifa_api/taarifa_api.py
```

The API started running in **192.168.1.223:5000**, when going to the browser and opening `http://192.168.1.223:5000/` shows a **404 Error**.

When running the `TaarifaTraders` I'm getting the same **404 Error**. I tried running it in different `hosts` and `ports`, but ended up with no luck.

```
sudo python manage.py runserver -r -d --> 127.0.0.1:5000
sudo python manage.py runserver -h 192.168.1.223 -r -d --> 192.168.1.223:5000
sudo python manage.py runserver -h 192.168.1.223 -p 90 -r -d --> 192.168.1.223:90
sudo python manage.py runserver -h 192.168.1.223 -p 8080 -r -d --> 192.168.1.223:8080
```

**Comment by fayazv** [comment]
@kynan, @dgorissen any suggestions on this?

**Comment by kynan** [comment]
@fayazv You should probably deploy it behind Gunicorn, nginx or something similar. See [Flask deployment options](http://flask.pocoo.org/docs/0.10/deploying/).

**Comment by fayazv** [comment]
Thanks @kynan. Will look into it.

**Comment by fayazv** [comment]
Got fed-up with _apache_ and used **nginx** to setup the platform on AWS with the following [documentation](http://www.tornadoweb.org/en/stable/guide/running.html).

**Comment by kynan** [comment]
Great to hear!
